import {
  Sprout,
  ShoppingCart,
  FileCheck,
  ScrollText,
  Truck,
  Smartphone,
  Scale,
  Calculator,
  WifiOff,
  Gavel,
  Unlock,
  LayoutDashboard,
  Map,
  Brain,
  Package,
  Mic,
  Users,
  Building2,
  Crown,
  Wallet,
  Receipt,
} from 'lucide-react';
import logoOcpv from '../../assets/logo_ocpv.png';

export const BOUNDED_CONTEXTS = {
  amont: {
    id: 'amont',
    badge: 'Amont',
    title: 'Le Producteur',
    tagline: 'Auto-régulation et logistique',
    description:
      'Le producteur initie la chaîne de valeur : déclaration de récolte, acceptation du cadre légal et prise en charge du risque logistique jusqu\'au Hub OCPV.',
    cardBg: 'bg-white dark:bg-[#1a1a1a]',
    border: 'border-green-500/50',
    glow: 'shadow-green-500/20',
    iconColor: 'text-green-500',
    badgeColor: 'text-green-500',
    ring: 'ring-green-500',
    icon: Sprout,
    actors: [
      { label: 'Producteur', icon: Sprout, detail: 'Propriétaire de la marchandise, acteur rural' },
    ],
    features: [
      {
        title: 'Déclaration de disponibilité',
        icon: FileCheck,
        detail: 'Signalement des volumes · création d’un Lot OCPV tracé jusqu’à la vente.',
      },
      {
        title: 'Récépissé QR de remise',
        icon: ScrollText,
        detail: 'Preuve obligatoire avant remise de la récolte à l’agent au point de ramassage.',
      },
      {
        title: 'Transfert du risque logistique amont',
        icon: Truck,
        detail: 'Le producteur assume le fret jusqu\'au Hub, auto-régulant les flux entrants.',
      },
      {
        title: 'Interface SMS / USSD',
        icon: Smartphone,
        detail: 'Canal dédié aux zones rurales en couverture 2G (*555#).',
      },
    ],
    demoLinks: [
      { label: 'Démo interface Producteur (App + USSD)', path: '/demo-producteur' },
    ],
  },
  ocpv: {
    id: 'ocpv',
    badge: 'Centre de gravité',
    title: 'OCPV',
    tagline: 'Tiers de confiance — Régulation, Contrôle & Intelligence',
    description:
      'L\'Office d\'Aide à la Commercialisation des Produits Vivriers orchestre le contrôle physique, la fiscalité, la résolution des litiges et le pilotage stratégique national.',
    cardBg: 'bg-white dark:bg-[#1a1a1a]',
    border: 'border-orange-500/60',
    glow: 'shadow-orange-500/25',
    iconColor: 'text-orange-500',
    badgeColor: 'text-orange-500',
    ring: 'ring-orange-500',
    logoSrc: logoOcpv,
    icon: Sprout,
    actors: [
      { label: 'Agent OCPV', icon: Scale, detail: 'Contrôle qualité, pesage et facturation TPE' },
      { label: 'Chef d\'Antenne', icon: Building2, detail: 'Supervision régionale et litiges' },
      { label: 'DGM', icon: Crown, detail: 'Pilotage stratégique et paramétrage fiscal' },
    ],
    features: [
      {
        title: 'TPE offline-first',
        icon: WifiOff,
        detail: 'Application embarquée : pesage, synchronisation différée, facturation hors ligne.',
        group: 'Terrain',
      },
      {
        title: 'Calcul automatique des taxes',
        icon: Calculator,
        detail: 'Côte Part, CP et APE calculés en temps réel depuis le contexte Core.',
        group: 'Terrain',
      },
      {
        title: 'Gestion des litiges',
        icon: Gavel,
        detail: 'Arbitrage des conflits transactionnels au niveau régional.',
        group: 'Région',
      },
      {
        title: 'Forçage légal de libération',
        icon: Unlock,
        detail: 'Pouvoir juridique du Chef d\'Antenne sur les marchandises bloquées.',
        group: 'Région',
      },
      {
        title: 'Tableau de bord DGM',
        icon: LayoutDashboard,
        detail: 'Vue consolidée des recettes, flux et indicateurs nationaux.',
        group: 'Stratégie',
        demo: '/dashboard-dgm',
      },
      {
        title: 'Heat Map nationale',
        icon: Map,
        detail: 'Indice d\'abondance régionale en temps réel — surplus vs pénurie.',
        group: 'Stratégie',
        demo: '/dashboard-dgm',
      },
      {
        title: 'IA de prédiction des prix',
        icon: Brain,
        detail: 'Modèles prédictifs J+7 / J+30 par produit et par région.',
        group: 'Stratégie',
      },
    ],
    demoLinks: [
      { label: 'Mockup TPE', path: '/tpe-mockup' },
      { label: 'Dashboard Antenne', path: '/dashboard-antenne' },
      { label: 'Dashboard DGM', path: '/dashboard-dgm' },
      { label: 'Architecture CP/APE (v1)', path: '/architecture-v1' },
    ],
  },
  aval: {
    id: 'aval',
    badge: 'Aval',
    title: "L'Acheteur & Marché",
    tagline: 'Achat, Paiement direct & Preuve OCPV',
    description:
      'L’acheteur paie le producteur directement (Mobile Money), présente la preuve de paiement au Hub OCPV pour les taxes CP/APE, avec timer réglementaire de 24 h pour confirmation.',
    cardBg: 'bg-white dark:bg-[#1a1a1a]',
    border: 'border-slate-300 dark:border-white/25',
    glow: 'shadow-white/10',
    iconColor: 'text-slate-700 dark:text-white',
    badgeColor: 'text-orange-400',
    ring: 'ring-orange-400',
    icon: ShoppingCart,
    actors: [
      { label: 'Acheteur B2B / B2C', icon: Users, detail: 'Grossistes et consommateurs finaux' },
      { label: 'Transporteur', icon: Truck, detail: 'Prestataire logistique sur la bourse intégrée' },
    ],
    features: [
      {
        title: 'Catalogue certifié',
        icon: Package,
        detail: 'Lots contrôlés OCPV avec décote dynamique (Yield Management).',
      },
      {
        title: 'Paiement direct producteur',
        icon: Wallet,
        detail: 'L’acheteur règle le producteur sur son compte Wave / OM / MTN — hors séquestre OCPV.',
      },
      {
        title: 'Preuve de paiement au hub',
        icon: Receipt,
        detail: 'L’acheteur présente la preuve au Hub OCPV : enregistrement, taxes CP/APE, timer 24 h.',
      },
      {
        title: 'Matchmaking IA par voix',
        icon: Mic,
        detail: 'Voice-to-JSON sur WhatsApp — dictée en langage naturel, structuration automatique.',
      },
    ],
    demoLinks: [
      { label: 'Démo Acheteur (catalogue & P2P)', path: '/demo-acheteur' },
      { label: 'Démo Transporteur (bourse fret)', path: '/demo-transporteur' },
    ],
  },
};

export const INITIAL_NODES = [
  {
    id: 'amont',
    type: 'boundedContext',
    position: { x: 24, y: 230 },
    data: { contextId: 'amont' },
  },
  {
    id: 'ocpv',
    type: 'boundedContext',
    position: { x: 370, y: 20 },
    data: { contextId: 'ocpv', isHub: true },
  },
  {
    id: 'aval',
    type: 'boundedContext',
    position: { x: 716, y: 230 },
    data: { contextId: 'aval' },
  },
];

export const INITIAL_EDGES = [
  {
    id: 'amont-ocpv',
    source: 'amont',
    sourceHandle: 'out-right',
    target: 'ocpv',
    targetHandle: 'in-left',
    type: 'animatedFlow',
    label: 'Flux vivrier + QR remise',
    animated: true,
    data: { flow: 'physical', labelPosition: 0.45, labelOffsetY: -28, labelOffsetX: -4, curvature: 0.28 },
  },
  {
    id: 'ocpv-aval',
    source: 'ocpv',
    sourceHandle: 'out-right',
    target: 'aval',
    targetHandle: 'in-left',
    type: 'animatedFlow',
    label: 'Catalogue certifié',
    animated: true,
    data: { flow: 'physical', labelPosition: 0.38, labelOffsetY: -32, labelOffsetX: 0, curvature: 0.28 },
  },
  {
    id: 'aval-amont-paiement',
    source: 'aval',
    sourceHandle: 'out-bottom',
    target: 'amont',
    targetHandle: 'in-bottom',
    type: 'animatedFlow',
    label: 'Paiement P2P direct',
    animated: true,
    data: { flow: 'financial', labelPosition: 0.5, labelOffsetY: 22, labelOffsetX: 0, curvature: 0.15 },
  },
  {
    id: 'aval-ocpv-preuve',
    source: 'aval',
    sourceHandle: 'out-left-mid',
    target: 'ocpv',
    targetHandle: 'in-right-low',
    type: 'animatedFlow',
    label: 'Preuve de paiement',
    animated: true,
    data: { flow: 'financial', labelPosition: 0.48, labelOffsetY: 8, labelOffsetX: -6, curvature: 0.35 },
  },
];
